version: "3.9"
services:
  api:
    build:
      context: ../..
      dockerfile: 08_DevOps/Dockerfile
    image: advanced-pack-api:latest
    environment:
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/healthz/ready || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_Strong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P $${SA_PASSWORD} -Q "SELECT 1" || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
