<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AssemblyName>Demo12_EfCoreSqlLeastPrivilege.Tests</AssemblyName>
    <RootNamespace>Demo12.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Shared\Demo12_Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\src\CodeFirst\appsettings.json" Link="codefirst-appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\src\DatabaseFirst\appsettings.json" Link="dbfirst-appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
